language: rust
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
    - stable
    - beta
os:
    - linux
    - osx
install:
    - source scripts/ci/setup-travis.sh
    - ./scripts/ci/install-travis.sh
    # Clean any cached test executable
    - rm -f target/debug/*-*
script:
    - cd $TRAVIS_BUILD_DIR
    # Run all tests in release mode
    - cargo test --all --release
    # Run unit tests and doc tests in debug mode
    - cargo test -p lumol-core
    - cargo test -p lumol-input
    # Check if tutorials compile
    - cd
    # Check that benchmarks still compile
    - cargo bench --no-run
    # Check if tutorials compile
    - ./scripts/ci/compile-tutorials.py
    # Misc style checking
    - ./scripts/ci/check-whitespaces.py
    # Generate and check doc
    - ./scripts/ci/generate-docs.sh
    - ./scripts/ci/check-html-book.py doc/book
    # Generate and publish coverage
    - |
      if ${DO_COVERAGE}; then
          for test in $(find target/debug/deps/ ! -name "lib*" -type f); do
              kcov --include-pattern=$(pwd) --exclude-pattern=target target/kcov $test
          done
          bash <(curl -s https://codecov.io/bash) -s target/kcov
      fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/gh-pages
  email: lumol-bot@lumol.org
  name: Lumol Bot
  on:
    os: linux
    rust: stable
    branch: master

cache:
  cargo: true
  directories:
      - $HOME/local/bin
