language: rust
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
    - stable
    - beta
os:
    - linux
    - osx
install:
    - source scripts/ci/setup-travis.sh
    - ./scripts/ci/install-travis.sh
    # Clean any cached test executable
    - mkdir -p target/debug/deps/  # just in case
    - find target/debug/deps/ ! -name "lib*" -type f -delete
script:
    - cd $TRAVIS_BUILD_DIR
    # Run all tests in release mode
    - cargo test --all --release -- --test-threads=2
    # Run unit tests and doc tests in debug mode
    - cargo test --all --lib -- --test-threads=2
    - cargo test --all --doc -- --test-threads=2
    - cargo test -p lumol-input --tests -- --test-threads=2
    # Check that benchmarks still compile
    - cargo bench --no-run
    # Check if tutorials compile
    - |
      for tutorial in tutorials/*/
      do
        cd $tutorial
        cargo build
        cd -
      done
    # Misc style checking
    - ./scripts/ci/check-whitespaces.py
    # Generate documentation and place it in target/gh-pages
    - ./scripts/ci/generate-docs.sh
    # Generate and publish coverage
    - |
      if ${DO_COVERAGE}; then
          for test in $(find target/debug/ -maxdepth 1 -executable -type f); do
              kcov --include-pattern=$(pwd) --exclude-pattern=target --exclude-pattern=tutorials target/kcov $test
          done
          bash <(curl -s https://codecov.io/bash) -s target/kcov
      fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/gh-pages
  email: lumol-bot@lumol.org
  name: Lumol Bot
  on:
    branch: master
    condition: "${TRAVIS_OS_NAME} == linux && ${TRAVIS_RUST_VERSION} == stable"

cache:
  directories:
      - $HOME/local/bin
