[package]
name = "lumol"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://lumol-org.github.io/lumol"
repository = "https://github.com/lumol-org/lumol"
readme = "README.md"
license = "BSD-3-Clause"
build = "src/build.rs"

[workspace]
members = [
	"lumol-core",
	"lumol-input",
]
exclude = ["tutorials"]

[[bin]]
name = "lumol"
path = "src/bin/lumol.rs"
doc = false

[dependencies]
lumol-input = {path = "lumol-input"}
lumol-core = {path = "lumol-core"}
log = "0.4"
clap = "2"
chrono = "0.4"

[dev-dependencies]
bencher = "0.1"
rand = "0.5"
env_logger = "0.5"

[[bench]]
name = "water"
harness = false

[[bench]]
name = "nacl"
harness = false

[[bench]]
name = "argon"
harness = false

[[bench]]
name = "propane"
harness = false
