[package]
name = "lumol"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://lumol-org.github.io/lumol"
repository = "https://github.com/lumol-org/lumol"
readme = "README.md"
license = "BSD"

[workspace]
members = [
	"src/core",
    "src/input",
    "src/macros",
]

[[bin]]
name = "lumol"
path = "src/bin/lumol.rs"
doc = false

[dependencies]
lumol-input = {path = "src/input"}
lumol-core = {path = "src/core"}
log = "0.3"
clap = "2"
