[package]
name = "lumol-core"
version = "0.0.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
documentation = "https://lumol.org/"
repository = "https://github.com/lumol-org/lumol"
readme = "../README.md"
license = "BSD-3-Clause"

[lib]
bench = false

[dependencies]
bitflags = "1"
chemfiles = "0.8"
lazy_static = "1"
log = "0.4"
log-once = "0.2"
ndarray = "0.12"
num-traits = "0.2"
rayon = "1"
soa_derive = "0.7"
special = "0.7"
thread_local = "0.3"

[dev-dependencies]
tempfile = "3"
approx = "0.3"
